# Generated by Django 4.2.2 on 2023-07-03 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='NAME')),
                ('description', models.CharField(max_length=30, verbose_name='DESCRIPTION')),
                ('image', models.ImageField(upload_to='userProfile/', verbose_name='IMAGE')),
                ('total', models.PositiveIntegerField(default=0, verbose_name='TOTAL')),
                ('realty', models.PositiveIntegerField(default=0, verbose_name='REALTY')),
                ('economy', models.PositiveIntegerField(default=0, verbose_name='ECONOMY')),
                ('selfDevelopment', models.PositiveIntegerField(default=0, verbose_name='SELFDEV')),
                ('discount', models.PositiveIntegerField(default=0, verbose_name='DISCOUNT')),
                ('commonSense', models.PositiveIntegerField(default=0, verbose_name='COMMONSENSE')),
                ('etc', models.PositiveIntegerField(default=0, verbose_name='ETC')),
                ('answerCount', models.PositiveIntegerField(default=0, verbose_name='ANWERCOUNT')),
                ('recommendCount', models.PositiveIntegerField(default=0, verbose_name='RECOMMENDCOUNT')),
                ('questionCount', models.PositiveIntegerField(default=0, verbose_name='QUESTIONCOUNT')),
            ],
        ),
    ]
