# Generated by Django 4.2.2 on 2023-07-13 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizApp', '0007_alter_quiz_category'),
        ('accounts', '0004_incorrectbydate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='correctbydate',
            name='count',
        ),
        migrations.RemoveField(
            model_name='incorrectbydate',
            name='count',
        ),
        migrations.AddField(
            model_name='correctbydate',
            name='quiz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quizApp.quiz'),
        ),
        migrations.AddField(
            model_name='incorrectbydate',
            name='quiz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quizApp.quiz'),
        ),
    ]
