# Generated by Django 4.2.2 on 2023-07-13 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_correctbydate_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correctbydate',
            name='date',
            field=models.DateTimeField(verbose_name='DATE'),
        ),
        migrations.AlterField(
            model_name='incorrectbydate',
            name='date',
            field=models.DateTimeField(verbose_name='DATE'),
        ),
    ]
