# Generated by Django 4.2.2 on 2023-07-13 04:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communicationApp', '0002_answer_comment_question_delete_club_comment_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_answer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='answer',
            name='recommend',
        ),
        migrations.AlterField(
            model_name='question',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_question', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answer',
            name='recommend',
            field=models.ManyToManyField(related_name='voer_question', to=settings.AUTH_USER_MODEL),
        ),
    ]
