# Generated by Django 4.2.2 on 2023-07-13 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communicationApp', '0004_alter_question_content_alter_question_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.PositiveIntegerField(verbose_name='CATEGORY'),
        ),
    ]
