# Generated by Django 4.2.2 on 2023-07-14 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communicationApp', '0006_alter_answer_question_alter_comment_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='recommend',
        ),
        migrations.AddField(
            model_name='answer',
            name='recommend',
            field=models.PositiveIntegerField(default=0, verbose_name='RECOMMEND'),
        ),
    ]
