# Generated by Django 4.2.2 on 2023-07-05 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100, verbose_name='TEXT')),
                ('description', models.CharField(max_length=40, verbose_name='DESCRIPTION')),
                ('category', models.CharField(max_length=20, verbose_name='CATEGORY')),
                ('difficulty', models.PositiveIntegerField(default=0, verbose_name='DIFFICULTY')),
                ('total', models.PositiveIntegerField(default=0, verbose_name='TOTAL')),
                ('incorrect', models.PositiveIntegerField(default=0, verbose_name='INCORRECT')),
                ('content', models.TextField(default=0, verbose_name='CONTENT')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
