# Generated by Django 4.2.2 on 2023-07-10 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizApp', '0002_remove_quiz_user_quiz_correct_alter_quiz_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='isCorrect',
            field=models.CharField(default='incorrectA', max_length=10, verbose_name='ISCORRECT'),
        ),
    ]
