# Generated by Django 4.2.2 on 2023-07-07 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizApp', '0003_choice_iscorrect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='isCorrect',
            field=models.CharField(default='incorrectA', max_length=10, verbose_name='ISCORRECT'),
        ),
    ]
