# Generated by Django 4.2.2 on 2023-07-10 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizApp', '0003_choice_iscorrect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='correct',
            field=models.CharField(max_length=10, verbose_name='CORRECT'),
        ),
    ]
