# Generated by Django 4.2.2 on 2023-07-13 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizApp', '0005_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='category',
            field=models.PositiveIntegerField(max_length=20, verbose_name='CATEGORY'),
        ),
    ]
